# Assignment: Numpy

Perform the follwing tasks:


In [1]:
#1: import the numpy library
import numpy as np

In [5]:
#2: create a random 10x10 array named A
A = np.random.rand(10,10)
A

array([[0.12735395, 0.28105595, 0.18382334, 0.30587723, 0.52003897,
        0.13076499, 0.31387036, 0.35774544, 0.2513004 , 0.19072431],
       [0.33234436, 0.13048012, 0.60524735, 0.41790808, 0.21463706,
        0.71661108, 0.01484588, 0.56657847, 0.48980018, 0.02167936],
       [0.49859419, 0.28674745, 0.59511444, 0.34507883, 0.96696896,
        0.33732852, 0.39505111, 0.34073488, 0.24313943, 0.00463524],
       [0.76300424, 0.11461913, 0.06046223, 0.54815431, 0.98402807,
        0.85709881, 0.43202958, 0.47416205, 0.39635541, 0.17840794],
       [0.08823966, 0.42771974, 0.1704262 , 0.90919779, 0.69790839,
        0.20689825, 0.58787978, 0.7220864 , 0.32024626, 0.59334795],
       [0.65481248, 0.50625093, 0.43840731, 0.61159653, 0.19671712,
        0.77724966, 0.72651144, 0.1757471 , 0.66370264, 0.77305401],
       [0.85767419, 0.51665864, 0.47690308, 0.70968752, 0.09855032,
        0.00230182, 0.93758193, 0.9642176 , 0.21555969, 0.4339665 ],
       [0.40665435, 0.2704433 , 0.6134306

In [11]:
#3: return only the odd rows of A
#!!!Umschreiben ohne Loop!!!
for i in range (1,11,2):
    print(A[i])


[0.33234436 0.13048012 0.60524735 0.41790808 0.21463706 0.71661108
 0.01484588 0.56657847 0.48980018 0.02167936]
[0.76300424 0.11461913 0.06046223 0.54815431 0.98402807 0.85709881
 0.43202958 0.47416205 0.39635541 0.17840794]
[0.65481248 0.50625093 0.43840731 0.61159653 0.19671712 0.77724966
 0.72651144 0.1757471  0.66370264 0.77305401]
[0.40665435 0.2704433  0.61343064 0.1737941  0.6373528  0.61637264
 0.21205432 0.2504001  0.51446941 0.30200633]
[0.25799151 0.36122816 0.19116091 0.19957421 0.6928996  0.51651135
 0.09504532 0.36128335 0.09114446 0.50572844]


In [13]:
#4: perform a matrix multiplication of A with it's transposed
B = A * np.transpose(A)
print(B)

[[1.62190293e-02 9.34073599e-02 9.16532479e-02 2.33385628e-01
  4.58880623e-02 8.56265440e-02 2.69198510e-01 1.45478737e-01
  9.21142224e-02 4.92052531e-02]
 [9.34073599e-02 1.70250615e-02 1.73553131e-01 4.79002600e-02
  9.18045058e-02 3.62785025e-01 7.67025244e-03 1.53227352e-01
  3.10757185e-01 7.83119462e-03]
 [9.16532479e-02 1.73553131e-01 3.54161199e-01 2.08642358e-02
  1.64796843e-01 1.47887288e-01 1.88401089e-01 2.09017215e-01
  1.46185119e-01 8.86076293e-04]
 [2.33385628e-01 4.79002600e-02 2.08642358e-02 3.00473145e-01
  8.94676151e-01 5.24198664e-01 3.06605997e-01 8.24065667e-02
  1.82720708e-01 3.56056225e-02]
 [4.58880623e-02 9.18045058e-02 1.64796843e-01 8.94676151e-01
  4.87076116e-01 4.07004275e-02 5.79357380e-02 4.60223785e-01
  2.44965474e-01 4.11130555e-01]
 [8.56265440e-02 3.62785025e-01 1.47887288e-01 5.24198664e-01
  4.07004275e-02 6.04117031e-01 1.67230192e-03 1.08325702e-01
  6.60419388e-01 3.99291172e-01]
 [2.69198510e-01 7.67025244e-03 1.88401089e-01 3.06605997e

In [27]:
#5: compute the matrix inverse of A
C = np.linalg.inv(A)
C

array([[-0.48761985, -0.58600851,  0.29539326,  0.40464749, -0.49577471,
         0.78921794,  0.45839983,  0.43837829, -0.98424426,  0.45402232],
       [ 6.98267696,  1.54179216,  1.38703436, -1.35518628, -3.06261455,
         2.57505025, -0.79545261, -5.33061588, -0.59340955,  2.2958465 ],
       [-3.22325314,  0.05772158,  1.02621383, -0.81310075,  1.02285983,
        -0.54923322,  0.22855183,  1.39583071,  0.28198438, -0.37819638],
       [-1.62950153,  0.57841287,  1.69637381, -0.33302923,  1.27546811,
         1.37220275, -0.70338241, -1.75859749, -0.74415122,  0.01431249],
       [-0.18085549, -0.70101141,  0.30347312,  0.28454552,  0.44605948,
        -0.43640905, -0.21185974,  0.89146461, -0.10950476, -0.02587644],
       [-0.02089059,  1.17055738,  0.08239626,  0.2941082 , -0.68103983,
        -0.04942233, -0.33525824, -1.85184703,  0.92704456,  0.54806808],
       [-0.31923181, -0.38214516, -0.29425825,  0.48499225, -0.03000645,
        -1.03052821,  0.46895529,  0.0797935 

In [33]:
A

array([[0.12735395, 0.28105595, 0.18382334, 0.30587723, 0.52003897,
        0.13076499, 0.31387036, 0.35774544, 0.2513004 , 0.19072431],
       [0.33234436, 0.13048012, 0.60524735, 0.41790808, 0.21463706,
        0.71661108, 0.01484588, 0.56657847, 0.48980018, 0.02167936],
       [0.49859419, 0.28674745, 0.59511444, 0.34507883, 0.96696896,
        0.33732852, 0.39505111, 0.34073488, 0.24313943, 0.00463524],
       [0.76300424, 0.11461913, 0.06046223, 0.54815431, 0.98402807,
        0.85709881, 0.43202958, 0.47416205, 0.39635541, 0.17840794],
       [0.08823966, 0.42771974, 0.1704262 , 0.90919779, 0.69790839,
        0.20689825, 0.58787978, 0.7220864 , 0.32024626, 0.59334795],
       [0.65481248, 0.50625093, 0.43840731, 0.61159653, 0.19671712,
        0.77724966, 0.72651144, 0.1757471 , 0.66370264, 0.77305401],
       [0.85767419, 0.51665864, 0.47690308, 0.70968752, 0.09855032,
        0.00230182, 0.93758193, 0.9642176 , 0.21555969, 0.4339665 ],
       [0.40665435, 0.2704433 , 0.6134306

In [32]:
#6: divide all entries of A which are lager than 0.5 by 2 (hint: use where() )

D= np.where(A>0.5, A/2, A)
D

array([[0.12735395, 0.28105595, 0.18382334, 0.30587723, 0.26001949,
        0.13076499, 0.31387036, 0.35774544, 0.2513004 , 0.19072431],
       [0.33234436, 0.13048012, 0.30262367, 0.41790808, 0.21463706,
        0.35830554, 0.01484588, 0.28328924, 0.48980018, 0.02167936],
       [0.49859419, 0.28674745, 0.29755722, 0.34507883, 0.48348448,
        0.33732852, 0.39505111, 0.34073488, 0.24313943, 0.00463524],
       [0.38150212, 0.11461913, 0.06046223, 0.27407715, 0.49201403,
        0.42854941, 0.43202958, 0.47416205, 0.39635541, 0.17840794],
       [0.08823966, 0.42771974, 0.1704262 , 0.4545989 , 0.34895419,
        0.20689825, 0.29393989, 0.3610432 , 0.32024626, 0.29667397],
       [0.32740624, 0.25312546, 0.43840731, 0.30579827, 0.19671712,
        0.38862483, 0.36325572, 0.1757471 , 0.33185132, 0.38652701],
       [0.4288371 , 0.25832932, 0.47690308, 0.35484376, 0.09855032,
        0.00230182, 0.46879097, 0.4821088 , 0.21555969, 0.4339665 ],
       [0.40665435, 0.2704433 , 0.3067153

In [15]:
#7: compute the singular value decomposition of A
#7.1: plot the singular values
#7.2: reconstruct A' by using only the top 5 singular values